baseURL = "http://viaphoniker.eu"
staticDir = ['static']
languageCode = "de-de"
enableGitInfo = true
title = "ViaphonikerInnen"
[markup.goldmark.renderer]
unsafe = true
[params]
custom_css = ["css/menu.css", "css/style.css"]

[imaging]
  quality = 85
  resampleFilter = "lanczos"


